/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   build_tools/sim_object_param_struct_hh.py:233
 */

#ifndef __PARAMS__MemCpyPioDevice__
#define __PARAMS__MemCpyPioDevice__

namespace gem5 {
class MemCpyPioDevice;
} // namespace gem5

#include "params/BasicPioDevice.hh"

namespace gem5
{
struct MemCpyPioDeviceParams
    : public BasicPioDeviceParams
{
    gem5::MemCpyPioDevice * create() const;
};

} // namespace gem5

#endif // __PARAMS__MemCpyPioDevice__
